site_name: Eggi

site_description: An ASGI framework with a little something for everyone. Let's start with an egg.🥚

theme:
  name: material
  logo: images/eggi-logo.png
  favicon: images/eggi-logo.png

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Reference: reference.md

watch:
  - eggi
